print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weight?", end=' ')
weight = input()
print("What is your current position?", end=' ')
position = input()

print(f"So, you're {age} years old, {height} tall and {weight} heavy. You're a/an {position}")