print("1 should be True:", True and True)
print("2 should be False:", False and True)
print("3 should be False:", 1 == 1 and 2 == 1)
print("4 should be True:", "test" == "test")
print("5 should be True:", 1 == 1 and 2 != 1)
print("6 should be True:", True and 1 == 1)
print("7 should be False:", False and 0 != 0)
print("8 should be True:", True or 1 == 1)
print("9 should be False:", "test" == "testing")
print("10 should be False:", 1 != 0 and 2 == 1)
print("11 should be True:", "test" != "testing")
print("12 should be False:", "test" == 1)
print("13 should be True:", not(True and False))
print("14 should be False:", not(1 == 1 and 0 != 1))
print("15 should be False:", not(10 == 1 or 1000 == 1000))
print("16 should be False:", not(1 != 10 or 3 == 4))
print("17 should be True:", not("testing" == "testing" and "Zed" == "Cool Guy"))
print("18 should be True:", 1 == 1 and (not("testing" == 1 or 1 == 0)))
print("19 should be False:", "chunky" == "bacon" and (not("testing" == 1 or 1 == 0)))
print("20 should be False:", 3 == 3 and not("testing" == "testing" or "Python" == "Fun"))